### ISSUE TITLE
Auto Focus on angular-summernote Occus when i use ng-model in the summernote tag

### ISSUE THREAD

**Issue by LuciferZhang** [summernote/angular-summernote#101]
<div summernote ng-model="resource.detail" config="options" id="detail"                                  name="detail"></div>

i want to use ng-model to bind a variable to $scope. But when i reload the page, auto focus on angular-summernote occurs.

anyone else has the same question?

**Comment by outsideris** [comment]
It is the issue that is related with https://github.com/summernote/summernote/pull/1569 . I confirmed it is fixed in `develop` branch of summernote. I expect it will be fixed in v0.7.2 of summernote.

**Comment by LuciferZhang** [comment]
Got It! Thanks
