### ISSUE TITLE
it has onimageupload & insertimage?

### ISSUE THREAD

**Issue by juhongchul** [summernote/angular-summernote#102]
i try to insert & onimageupload event in summernote.

but it can't

i found some document at this site. i.. can't see insert & onimageupload event.
only i can see that  $scope.imageUpload = function(files) {
    console.log('image upload:', files);
    console.log('image upload\'s editable:', $scope.editable);
  }..
i'm wrong? please let me know. 
thank you very much.

**Comment by outsideris** [comment]
You need to upload the image into your server and make a image node and then insert it in editor.

```
<summernote on-image-upload="imageUpload(files)" editor="editor"></summernote>

$scope.imageUpload = function(files) {
  // upload images to your server
  var imgNode = $('<img>').attr('src', 'https://assets-cdn.github.com/images/modules/dashboard/bootcamp/octocat_setup.png')[0];
  $scope.editor.summernote('insertNode', imgNode);
};
```

**Comment by juhongchul** [comment]
wow..thanks a lot

**Comment by iit2011081** [comment]
I have initialized summernote as an attribute like this 
```
<div summernote config="options" ng-model='about' ng-if="showEditor" editor="editor" on-image-upload="imageUpload(files)">
	<p ng-bind-html="about"></p>
</div>
```

When I'm uploading image it give me following error.
Cannot read property 'summernote' of undefined. 

I tried to insert image url like this.
$scope.editor.summernote('insertNode', imgNode);
