### ISSUE TITLE
Double editor window in IE on load

### ISSUE THREAD

**Issue by virtser** [summernote/angular-summernote#103]
I'm getting double editor window in Internet Explorer 10 & 11.

My directive is declared as: ```<summernote config="options" ng-model="notification.content"/>```

See the issue here:
![sauce labs manual test](https://cloud.githubusercontent.com/assets/468590/12265298/00e678e2-b945-11e5-999c-f74493b6001c.png)

**Comment by Jeroen06** [comment]
I have the same problem, there is another ticket describing the same problem with the double editor in IE11: https://github.com/summernote/angular-summernote/issues/98, hopefully this can be fixed soon I checked the code but I could not fix the problem unfortunately.

**Comment by outsideris** [comment]
It will be managed in #98 even if initial post is Korean.
