### ISSUE TITLE
Triggering "undo" on first load causes Summernote to be blank. 

### ISSUE THREAD

**Issue by nwpan** [summernote/angular-summernote#110]
Hey all -- I've ran into a bug that affects the the first "undo" of Summernote. When you trigger an "undo" upon loading, the text gets set to a blank value. This affects the History stack of Summernote, causing a strange behaviour. I'm proposing a fix (see PR [here](https://github.com/summernote/angular-summernote/pull/109)).

For a example, I've provided two scripts below... First is the original directive (loading Angular Summernote from CDN). The second is my modified fix, proposed at the above PR. Please see here:
* http://jsfiddle.net/kauypdyb/3/
* http://jsfiddle.net/x9ra1x7r/3/

Steps to reproduce:
1. Click the [first link](http://jsfiddle.net/kauypdyb/3/).
2. Press either CTRL+Z or press the backarrow undo button within the toolbar.
3. Notice that the text field becomes blank.

This issue affects when you select a text range, then **bold the text**, then press undo. In the native demo (without Angular), you are also not able to undo to a blank space. 

Specifically, this problem has to do with using the [transclude: 'element']: [here](https://github.com/summernote/angular-summernote/blob/master/src/angular-summernote.js#L133). As per this StackOverflow discussion ([here](http://stackoverflow.com/questions/18449743/angularjs-when-to-use-transclude-true-and-transclude-element)), we cannot have access to the scope because it hasn't been created yet. Specifically in the link function, we're passing an empty model into this function. Then we continue and activate the SummernoteController.

Instead, we need to yield and wait until the scope gets created. In my proposed change, I have checked if there is a model provided (a blank one), then watch for a change. I've also added a unit test to check when the Summernote element's HTML is blank. Please let me know what you guys think, or if there's a better approach to this.

Cheers,

Nick
:coffee:

**Comment by outsideris** [comment]
fixed in #109

**Comment by snehagupta614** [comment]
hey can u please provide me with the same solution for summernote v0.8.2 and not for angular-summernote
