### ISSUE TITLE
Does angular-summernote support angular 1.5?

### ISSUE THREAD

**Issue by billyaraujo** [summernote/angular-summernote#115]
If so, can you update bower.json to reflect this?

**Comment by simonlinj** [comment]
Yes, we are running it with angular 1.5

**Comment by outsideris** [comment]
@simonlinj Thank you for your information.
@billyaraujo I missed the release schedule for angular 1.5. I should change primary target to angular 1.5 from angular 1.4 while keep to compatible with angular 1.4.
I will fix it soon.

**Comment by billyaraujo** [comment]
@outsideris  thanks.
