### ISSUE TITLE
It seems a typo in readme.md

### ISSUE THREAD

**Issue by CheolJeJo** [summernote/angular-summernote#116]
' fontface ' -> ' fontname '
' textsize ' -> ' fontsize '

## options object

```
function DemoController($scope) {
  $scope.options = {
    height: 300,
    focus: true,
    airMode: true,
    toolbar: [
            ['edit',['undo','redo']],
            ['headline', ['style']],
            ['style', ['bold', 'italic', 'underline', 'superscript', 'subscript', 'strikethrough', 'clear']],
            ['fontface', ['fontname']], //--- typo error ---> ['fontname', ['fontname']],
            ['textsize', ['fontsize']], //--- typo error ---> ['fontsize', ['fontsize']],
            ['fontclr', ['color']],
            ['alignment', ['ul', 'ol', 'paragraph', 'lineheight']],
            ['height', ['height']],
            ['table', ['table']],
            ['insert', ['link','picture','video','hr']],
            ['view', ['fullscreen', 'codeview']],
            ['help', ['help']]
        ]
  };
}
```

**Comment by outsideris** [comment]
Did you use airmode?

**Comment by CheolJeJo** [comment]
I did not use the airmode.
I solved the problem by modifying the name of the property.
'fontface' -> 'fontname'
'textsize' -> 'fontsize'
It seems a typo in readme.md

**Comment by outsideris** [comment]
@CheolJeJo Thank for updating the title.

In this [demo](http://jsfiddle.net/outsider/n8dt4/292/), it works with same options as README.
What is the problem that you experienced before fixing the name of properties.
I can't reproduce the problem. What is your OS and browser?

**Comment by CheolJeJo** [comment]
I use a Mac OS X 10 and Chrome 48.0
I will try some more tests.
And I'll write a article again.

**Comment by outsideris** [comment]
@CheolJeJo Thank you. I will wait for your reply.

**Comment by CheolJeJo** [comment]
I used the lower version of summernote.
I have updated to the latest version
It works well
Thank you :)

**Comment by outsideris** [comment]
Good. Thank you.
