### ISSUE TITLE
Upgrade to release 0.8.0

### ISSUE THREAD

**Issue by billyaraujo** [summernote/angular-summernote#117]
After updating to release 0.8.0 I noticed typing inside angular-summernote control is much slower (even with only about 20 lines). I downgraded to angular-sommernote 0.7.1 and it is now fine.

There seems to be some more processing going on in release 0.8.0.

**Comment by outsideris** [comment]
@billyaraujo There was an issue that reactivates editor when ngModel are updated. Sorry, for it takes a long time to fix the problem. Please check with v0.8.1.

**Comment by billyaraujo** [comment]
Sounds great. Thanks for the update.
