### ISSUE TITLE
Custom Buttons?

### ISSUE THREAD

**Issue by luncht1me** [summernote/angular-summernote#118]
[Summernote has Documentation on custom buttons here](http://summernote.org/deep-dive/#custom-button)

Can we, or is this implemented with this plugin? I'd love to have a couple custom buttons but having hard time getting it to work.

**Comment by outsideris** [comment]
@luncht1me You can add it with [option object](https://github.com/summernote/angular-summernote#options-object) like:

```
<div ng-controller="OptCtrl">
  <summernote config="options"></summernote>
</div>
```

```
var HelloButton = function (context) {
  var ui = $.summernote.ui;

  // create button
  var button = ui.button({
    contents: '<i class="fa fa-child"/> Hello',
    tooltip: 'hello',
    click: function () {
      // invoke insertText method with 'hello' on editor module.
      context.invoke('editor.insertText', 'hello');
    }
  });

  return button.render();   // return button as jquery object
}

angular.module('summernoteDemo', ['summernote'])
    .controller('OptCtrl', function($scope) {
      $scope.options = {
        toolbar: [
          ['mybutton', ['hello']]
        ],
        buttons: {
          hello: HelloButton
        }
      };
    });
```

**Comment by Emidomenge** [comment]
@outsideris,  I tried your example. It displays the hello button well but  I've got an error when I click on it : 

`Uncaught TypeError: Cannot read property 'invoke' of undefined`

on this line `context.invoke('editor.insertText', 'hello');`

Have you any idea to solve it ?

I'm using : 
```
"summernote": "^0.7.3",
"angular-summernote": "^0.7.1"
```

**Comment by outsideris** [comment]
@Emidomenge I guess it's is a bug in summernote v0.7.x.

**Comment by Emidomenge** [comment]
@outsideris Indeed, using last release it works good. But then, I have [this issue](https://github.com/summernote/summernote/issues/1676). All my icons are missing in my dist folder. :(

**Comment by outsideris** [comment]
I got it. I will be handled in summernote.
