### ISSUE TITLE
updateNgModel CPU Usage

### ISSUE THREAD

**Issue by lJakel** [summernote/angular-summernote#119]
I am having major performance issues with angular-summernote. 0.7.3 had much better performance but still almost unusable. updateNgModel gets called 8-15 times per key stroke. Even with ng-model-options. After typing about 15 characters, updateNgModel was called over 2000 times and browser froze (latest chrome). I am using the latest Summernote and latest Angular-Summernote.

```
<summernote
ng-model-options="{ updateOn: 'blur' }"
config='{"toolbar":[["style",["bold","italic","underline","clear"]],["para",["ul","ol"]],["view",["fullscreen","codeview"]]]}'
height="180"
ng-model="m.Title"></summernote>
```

**Comment by lJakel** [comment]
Changing the link function to this works as intended. Debouncing doesn't work because you are updating the model anyway using the onchange callback. You were also attaching a watch every time the model value changes. I also didn't understand why you were appending the data every time it changed. This new link function works perfectly and the performance is perfect.
```
  link: function(scope, element, attrs, ctrls, transclude) {
      var summernoteController = ctrls[0];
      var ngModel = ctrls[1];

      if (!ngModel) {
          transclude(scope, function(clone, scope) {
              // to prevent binding to angular scope (It require `tranclude: 'element'`)
              element.append(clone.html());
          });
      }
      summernoteController.activate(scope, element, ngModel);
  }
```

**Comment by elaijuh** [comment]
yup, the frequent DOM mutation blow me off

**Comment by outsideris** [comment]
I guess that recent pull requests decrease performance. Sorry for that fixing the issue takes a pretty long time. Thank you for deeply test for it. I will fix it soon.

**Comment by outsideris** [comment]
@lJakel Your snippets are very helpful to fix this issue. Thank you.

**Comment by lJakel** [comment]
Great @outsideris
Now let's fix the debounce! :D

**Comment by outsideris** [comment]
@lJakel I will make an issue for it.
