### ISSUE TITLE
Passing airMode =  true in $scope.options overrides all other configs that are in options object.

### ISSUE THREAD

**Issue by sanketmehta7** [summernote/angular-summernote#122]
`$scope.options = {
		    height: 300,
		    toolbar: [
		            ['edit',['undo','redo']],
		            ['headline', ['style']],
		            ['style', ['bold', 'italic', 'underline', 'superscript', 'subscript', 'strikethrough', 'clear']],
		            ['fontface', ['fontname']],
		            ['fontclr', ['color']],
		            ['alignment', ['ul', 'ol', 'paragraph', 'lineheight']],
		            ['insert', ['link','hr']]
		        ],
		    airMode: true
		  }`

And html
`<div summernote config="formAdd.options"></div>`
This shows airMode popup with only default airmode options.

**Comment by lJakel** [comment]
Works for me using this

```
<summernote name="lolcats" config='m.options' ng-model="m.Author1Bio"></summernote>

  m.options = {
            height: 300,
            airMode: true,
            airPopover: [
               ['color', ['color']],
               ['font', ['bold', 'underline', 'clear']],
               ['para', ['ul', 'paragraph']],
               ['table', ['table']],
               ['insert', ['link', 'picture']]
            ]
         };
```

**Comment by sanketmehta7** [comment]
Yes it is "controller as"
JS code
```javascript
angular.module('feedbackApp', ['summernote'])
	  .controller('MyFormController', function() {
               var formAdd = this;
               formAdd.options = {
		    height: 300,
		    toolbar: [
		            ['edit',['undo','redo']],
		            ['headline', ['style']],
		            ['style', ['bold', 'italic', 'underline', 'superscript', 'subscript', 'strikethrough', 'clear']],
		            ['fontface', ['fontname']],
		            ['fontclr', ['color']],
		            ['alignment', ['ul', 'ol', 'paragraph', 'lineheight']],
		            ['insert', ['link','hr']]
		        ],
		    airMode: true
		  };
         });
```
HTML code
```html
<div class="wells addnote" ng-controller="MyFormController as formAdd">
      <div summernote config="formAdd.options" placeholder="And rest goes here...." ng-model="formAdd.body"></div>
</div>
```

**Comment by sanketmehta7** [comment]
Also how to enable hint for emojis feature of summernote with this?

**Comment by lJakel** [comment]
So am I, you need to use below per summernote's api. airPopover not toolbar
airMode: true,
airPopover: []

**Comment by sanketmehta7** [comment]
Tried that too but no success. Also with every new update (typing), response get slower, I think there is some leak.

**Comment by lJakel** [comment]
Angular summernote 0.8.1 fixes the typing.

**Comment by sanketmehta7** [comment]
ok let me upgrade, thanks buddy. Upgrading might resolve the prior issue may be.

**Comment by sanketmehta7** [comment]
Still airmode issue persist.

**Comment by lJakel** [comment]
Here is a workaround.
```
options = {
    airMode: true,
    popover: {
      air: [
        ['color', ['color']],
        ['font', ['bold', 'underline', 'clear']],
      ]
    }
```

**Comment by sanketmehta7** [comment]
fixed thanks
