### ISSUE TITLE
Every change in the editor causes a new instance to be created, causing slow destoy

### ISSUE THREAD

**Issue by frederikheremans** [summernote/angular-summernote#123]
Hi, i'm using the `0.8.0` version of `angular-summernote` (combined with `angular-bootstrap`, not sure if it's relevant).

I'm using the ng-model approach to bind the edited HTML to a value in the scope of my own directive, using the summernote directive. This value is initialised with a value from a REST response and set, before the directive is included (using ng-if). Editing and saving the content afterwards (using the onChage callback) works fine. 

However, when destroying the scope, I noticed a long delay *sometimes*. After diving into this, I narrowed the delay down to the fact that there were multiple instances of summernote active for the element (when debugging, saw a number of _destroy calls in the summernote context, all containing their own memo's and modules).

Every time I did a change in the editor (eg. type some text, add newline, ...), the `$watch` (defined in the summernote derective's) triggers a call to `activate`, which passes the options to the raw `element.summernote(`.

```
 scope.$watch(function() {
              return ngModel.$viewValue;
            }, function(value) {
              element.append(value);
              summernoteController.activate(scope, element, ngModel);
            }, true);
          }
```

====

I'm not sure if I'm using the ng-model approach wrong (I can confirm that I am not changing the value in my model, on which the ng-model is bound).

For now, I'm using a patched version of angular-summernote, only calling the `activate` the first time in the $watch callback function, since I still want to have the result of the editing stored in my model.

**Comment by frederikheremans** [comment]
This is related to the way the `link` function works and fixed as part of #119 

Thanks!

**Comment by outsideris** [comment]
@frederikheremans You got a point of the issue. :+1:  Sorry for your wasted your time to dig the problem and source. I fixed it just a few days ago.

**Comment by frederikheremans** [comment]
No worries, just upgraded to `0.8.1` this morning and got rid of my workaround. Thanks for fixing!
