### ISSUE TITLE
Unable to use angular-summernote correctly

### ISSUE THREAD

**Issue by Emidomenge** [summernote/angular-summernote#135]
I downloaded 
```
bower install summernote --save
bower install angular-summernote --save
```

I add to my app.js : 
`'summernote'`

Then, in my html file : 
`<summernote ng-model="articleContent"></summernote>`

I've got this error in my console :  
`angular.js:13642 TypeError: $node.attr(...).tooltip is not a function`

I guess, I missed something while downloading ? I checked everywhere ...

Here some info : 

In my bower.json : 
```
"angular-summernote": "^0.8.1",
"summernote": "^0.8.1"
```

Note : 
Maybe the problem is because I'm using[ UI Bootstrap - AngularUI](https://www.google.fr/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjls5PX64PNAhXJrxoKHYVpAsMQFggcMAA&url=https%3A%2F%2Fangular-ui.github.io%2Fbootstrap%2F&usg=AFQjCNGDCw2gdtcbU376aNoaHv7rtS6hcA&sig2=qY_BCwXzQCNG5M6wGA42Mw&bvm=bv.123325700,d.d2s) instead of [Bootstrap Javascript](http://getbootstrap.com/javascript/)

Thanks for your help

**Comment by Emidomenge** [comment]
Ok I solved it myself. I need to add : 
`<script src="bower_components/bootstrap/dist/js/bootstrap.js"></script>`

**Comment by outsideris** [comment]
Good!

**Comment by YaroslavG** [comment]
@Emidomenge,
Hi, I have the same problem as you! It is a right solution to include script bootstrap?

**Comment by tinhnqjp** [comment]
Good!
