### ISSUE TITLE
How to show the preview of summernote content edited?

### ISSUE THREAD

**Issue by Thilak8654** [summernote/angular-summernote#138]
i have used ng-model and {{expression}} to show the preview. but it shows with html tags and image in some other format which doesn't display the image. how to display the content which also includes images without html tags .
```
<button class="btn btn-primary saveBtn" ng-click="saveContent()">Save</button>
<summernote id="editor" height="400" ng-model="meditationDesc" on-image-upload="imageUpload(files)"></summernote>
<div class="preview" ng-show="item == 'preview'">
        {{meditationDesc}}
</div>
```
can anyone please help me on this.

**Comment by scne** [comment]
up

**Comment by Thilak8654** [comment]
[Answer here](http://stackoverflow.com/questions/37656714/how-to-show-the-preview-of-summernote-editor-data-including-images-and-format-in)
