### ISSUE TITLE
when i use on-image-upload and  editable="editable" editor="editor" ,why $scope.editor is undefined?

### ISSUE THREAD

**Issue by laiyituan** [summernote/angular-summernote#142]
i use summernote v0.8.1 and chrome:
`<summernote ng-model="editItem.description" on-image-upload="imageUpload(files)" editable="editable" editor="editor" height="300"></summernote>`

` $scope.imageUpload = function(files) {
    console.log('image upload:', files);
    console.log('image upload\'s editor:', $scope.editor);
    console.log('image upload\'s editable:', $scope.editable)};`

i got this:
image upload: FileList {0: File, length: 1}
image upload's editor: undefined
image upload's editable: undefined

Am i losing something?

**Comment by girlssun** [comment]
i have the same problem,have you solved that?

**Comment by CicciMTS** [comment]
same problem, anyone solved that?

**Comment by MissCuriosity** [comment]
same problem, anyone solved that?
