### ISSUE TITLE
multiple editors in one .html file

### ISSUE THREAD

**Issue by blackmatch** [summernote/angular-summernote#145]
hello,
I want to init two summernote instance in one html file. And I user two <summernote> tags ang binding different config(like:$scope.summernoteConfig1,$scope.summernoteConfig2) and on-image-upload(uploadImage1,uploadImage2) functions. But when the second summernote editor show(binding with $scope.summernoteConfig2 and uploadImage2), the uploadImage2 function can not be called.

my main code:

html code:
`<summernote config="summernoteConfig" ng-model="newNoteObj.content" on-image-upload='imageUpload(files)' editable="editable" editor="editor"></summernote>`

`<summernote config="summernoteConfig2" ng-model="shareModalParams.content" on-image-upload='imageUpload2(files)' editable="editable" editor="editor2"></summernote>`

js code:
$scope.summernoteConfig = {
        dialogsInBody: true,
        toolbarContainer: '#summernote-toolbar',
        placeholder: '正文',
        height: 250,
        minHeight: 100,
        maxHeight: 300,
        focus: true,
        toolbar: [
            ['style', ['style']],
            ['fontsize', ['fontsize']],
            ['font', ['bold', 'italic', 'underline', 'strikethrough', 'color']],
            ['para', ['ol', 'ul', 'paragraph']],
            ['link', ['link', 'picture']],
            ['table', ['hr', 'table']]
        ],
    };

$scope.summernoteConfig2 = {
        dialogsInBody: true,
        toolbarContainer: '#summernote-toolbar2',
        placeholder: '正文',
        height: 200,
        minHeight: 100,
        maxHeight: 220,
        focus: true,
        toolbar: [
            ['style', ['style']],
            ['fontsize', ['fontsize']],
            ['font', ['bold', 'italic', 'underline', 'strikethrough', 'color']],
            ['para', ['ol', 'ul', 'paragraph']],
            ['link', ['link', 'picture']],
            ['table', ['hr', 'table']]
        ],
    };

$scope.imageUpload = function(files, event) {
        var file = files[0];
        GlobalFunctions.uploadFile(file, function(link) {
            var imgNode = $('<img>').attr('src', link)[0];
            $scope.editor.summernote('insertNode', imgNode);
        }, function() {
            GlobalFunctions.defAlert("很抱歉，图片上传失败");
        });
    };

$scope.imageUpload2 = function(files) {
        var file = files[0];
        alert(000);  //this function not be called
        GlobalFunctions.uploadFile(file, function(link) {
            var imgNode = $('<img>').attr('src', data.link)[0];
            $scope.editor2.summernote('insertNode', imgNode);
        }, function() {
            GlobalFunctions.defAlert("很抱歉，图片上传失败");
        });

any idea about this? Who can tell me how to init two summernote editor in one html file?

**Comment by dieguittom** [comment]
Hello,
I'm also having the same problem.
I have a page with two Summernote components, but only can perform the function of on-image-upload event in one of the components.

Please someone could help me.

Thank you.

**Comment by blackmatch** [comment]
@dieguittom I modify the source code to solve this problem.I set up  the 'open file dialog' button with a timestamp id,so if you have two or more summernote instance in one html file, they have different id, and then I bind the click event by id (using jquery selector).It works.

**Comment by dieguittom** [comment]
@blackmatch Thanks for your comment.

Please, could you show me how you did it in the source code?

Thank you.

**Comment by blackmatch** [comment]
@dieguittom 
I modify summernote.js like below:
![11111](https://cloud.githubusercontent.com/assets/12443954/18112776/d1038af6-6f5c-11e6-9c5f-bdc8ab53fdde.png)
![222222](https://cloud.githubusercontent.com/assets/12443954/18112780/d9b5aca6-6f5c-11e6-93b5-d6339dc0c80f.png)

**Comment by dieguittom** [comment]
@blackmatch  I made the change as you passed me, but it still fails.

You could perform the function of on-image-upload event after this change in both summernote. components?

Thank you for your help.

**Comment by blackmatch** [comment]
`<summernote config="summernoteConfig" ng-model="newNoteObj.content" on-image-upload='imageUpload(files)' editable="editable" editor="editor">
				</summernote>
<summernote config="summernoteConfig2" ng-model="shareModalParams.content" on-image-upload='imageUpload2(files)' editable="editable" editor="editor2">
				</summernote>`

@dieguittom

**Comment by dieguittom** [comment]
@blackmatch 

I was able to solve the problem in a different way. Without using the editor

If you are interested to see how I did, check issue https://github.com/summernote/angular-summernote/issues/150 where I posted the resolution

Thank you.

**Comment by Anandhakrishnan02** [comment]
I've added four summary notes on a page and after saving the content in that only one summary note is displaying and the other three is showing like a box. how to solve this
