### ISSUE TITLE
How to use "dialogsInBody: true" within angular-summernote

### ISSUE THREAD

**Issue by cmtest0000** [summernote/angular-summernote#151]
I want place the dialogs in body.
I have tried `<summernote dialogs-in-body="true"></summernote>`
but it's not work.

**Comment by cmtest0000** [comment]
I tried `<summernote dialogsinbody></summernote>` , but it's not work too.

**Comment by cmtest0000** [comment]
I use bower to installed this directive, but the file under dist is older version. 
It's not include "dialogsinbody".

**Comment by yeraycaballero** [comment]
Right, the file under this is an older version. 
I was able to setup that option in the configuration though

component.js
   ```
this.config: {
        airMode: true,
        disableDragAndDrop: true,
        dialogsInBody: true
 },
```
template.html
   ```
<summernote config="$ctrl.config"></summernote>
   ```
