### ISSUE TITLE
Manually trigger a model update?

### ISSUE THREAD

**Issue by tomskip123** [summernote/angular-summernote#165]
Hi,

bellow is my config for my summernote atm. 

```
$rootScope.globalEditorConfig = {
            height: 300,
            popover: {
                link: [
                    ['link', ['linkDialogShow', 'unlink']]
                ],
                air: [
                    ['color', ['color']],
                    ['font', ['bold', 'italic', 'underline', 'clear']],
                    ['extFct', ['pageSelect', 'link']]
                ]
            },
            toolbar: [
                ['style', ['bold', 'italic', 'underline', 'clear']],
                ['font', ['strikethrough', 'superscript', 'subscript']],
                ['fontsize', ['fontsize']],
                ['color', ['color']],
                ['para', ['ul', 'ol', 'paragraph']],
                ['height', ['height']]
            ],
            buttons: {
                pageSelect: pageSelect
            },
            dialogsInBody: true,
            dialogsFade: true
        };

        function pageSelect(context) {
            var ui = $.summernote.ui;

            var button = ui.button({
                contents: '<i class="fa fa-file-o" />',
                tooltip: 'Link Select',
                click: function () {
                    page
                        .get(')
                        .then(function (data) {

                            var m = modal.open({
                                templateUrl: 'path/to/view.html',
                                controller: 'controller',
                                size: 'lg'
                            });

                            m.result.then(function (result) {
                                //find highlighted text and replace with new content
                                var highlight = window.getSelection(),
                                    anchor = document.createElement('a'),
                                    selected = highlight.getRangeAt(0);

                                anchor.innerHTML = highlight;
                                anchor.setAttribute('href', '/' + result.slug);
                                anchor.setAttribute('ybt-nav-off-when-back', 'true');

                                // oldA.deleteContents();
                                selected.deleteContents();
                                selected.insertNode(anchor);

                                // got the data back from the service and updated the summernote view now i need to update the model
                                context.triggerEvent('focus');

                            });

                        });
                }
            });

            return button.render();
        }
```

the problem is when the data comes back from the service and i need to update the model. 
I'm now blind guessing which is not very productive.

Am i missing something? is this possible? 

I saw that you added an updateNgModel() function patch for onFocus and onChange a while ago maybe i can manually trigger these events. Or call the updateNgModel() function manually.

Thanks in advance

**Comment by tomskip123** [comment]
OK, so it seems I've managed to find a temporary solution with this

`$('.note-editable').trigger('input')`

which seems to trigger the update of the model (only problem is it will do it for all summernote instances on the current page) 

Maybe a feature request, if there isn't already one, a way to call the updateNgModel maybe through the summernote plugin feature?

Thanks, really good, easy to use angularjs plugin by the way.

**Comment by ecommgeek** [comment]
I'm having a similar problem, when I add an image or link and it's the last thing I do it doesn't update the model.  If I click the bold button for example it updates the model.  Unfortunately the trigger input solution didn't seem to do anything for me.

I'm using summernote JS/CSS 0.8.3 and angular-sumernote 0.8.1 

any ideas?

**Comment by tomskip123** [comment]
I've been using Angular 2 so this is going back for me, lets see. 
have you tried putting the trigger in a timeout?

**Comment by ecommgeek** [comment]
As in a setTimeout? No, I tried executing it with a button outside of the editor.

**Comment by tomskip123** [comment]
Can you post some code please

**Comment by ecommgeek** [comment]
Thanks for taking a look!  The code is part of one of our large internal systems so I'll post the code I added for the editor.

The HTML page:

```
    <link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.3/summernote.css" rel="stylesheet">
    <script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.3/summernote.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular-summernote/0.8.1/angular-summernote.js"></script>

@*Help content container*@
                    <div class="panel-body">
                        <div class="box wide">
                            <p ng-show="!Layout.helpEditMode" ng-bind-html="Layout.help.pageContent"></p>
                        </div>
                        <div class="box wide" ng-show="Layout.helpEditMode">
                            @*Tag for the rich text editor to use*@
                            <summernote height="300" ng-model="Layout.help.pageContent"></summernote>
                        </div>
                    </div>
                </div>

@*Edit link buttons*@
            <div class="SaveCancelHelpButton">
                <a href="#" class="btn btn-info btn-lg" ng-click="Layout.addLink()" ng-show="Layout.helpEditMode">
                    <span class="glyphicon glyphicon-plus"></span> Add Link
                </a>
                <a href="#" class="btn btn-info btn-lg" ng-click="Layout.saveHelp()" ng-show="Layout.helpEditMode">
                    <span class="glyphicon glyphicon-floppy-save"></span> Save
                </a>
                <a href="#" class="btn btn-info btn-lg" ng-click="Layout.cancelEdit()" ng-show="Layout.helpEditMode">
                    <span class="glyphicon glyphicon-remove"></span> Cancel
                </a>
            </div>

```
The Javascript:
`$('.summernote').summernote({
                    height: 300,                 // set editor height
                    minHeight: null,             // set minimum height of editor
                    maxHeight: null,             // set maximum height of editor
                    dialogsInBody: true
                });


//Save new/updated help content
            Layout.saveHelp = function () {
                $('.note-editable').trigger('input')
                var updateObj = {};
                updateObj.applicationID = urlKey.applicationID;
                updateObj.pageKey = urlKey.key;
                updateObj.pageContent = Layout.help.pageContent;
                updateObj.pageTitle = Layout.help.pageTitle;
                Layout.updateContent(updateObj)
                Layout.helpEditMode = false;
            }
`

**Comment by tomskip123** [comment]
Aren't you executing the trigger before you update the model? shouldn't that be after? 

Also try $('.summernote').trigger('summernote.change');

If it helps and maybe to save a lot of time and frustration I made my own.

DIRECTIVE:
`

    (function () {
       "use strict";

    angular
        .module('app')
        .directive('summerEdit', SummerEdit);

    SummerEdit.$inject = [];

    function SummerEdit() {

        var directive = {
            restrict: 'EA',
            scope: {
                ngModel: '=ngModel',
                editHeight: '=editHeight',
                summerConfig: '=summerConfig',
                noHtml: '=noHtml',
                fullMode: '=fullMode',
                saveChange: '=reset',
                isChanging: '=isChanging',
                reset: '=reset',
                originalBind: '=originalBind'
            },
            link: link,
            controller: controllerFunc,
            bindToController: true,
            controllerAs: 'vm'
        };

        return directive;

        function link(scope, elem, attr) {

        }
    }

    controllerFunc.$inject = [
        "$scope",
        "$element",
        '$timeout',
        '$uibModal',
        'PageService'
    ];

    function controllerFunc(scope,
                            elem,
                            $timeout,
                            modal,
                            page) {

        var _this = this;

        var options = {
            airMode: true,
            callbacks: {
                onChange: onChange
            }
        };

        if (_this.fullMode) {
            options.airMode = false;
            options.height = 300;
        }

        $timeout(function () {
            elem.summernote(options);
        }, 200);

        function onChange() {
                _this.ngModel = elem.summernote('code'); // updating here
        }

        scope.$on('$destroy', function () {
            elem.summernote('destroy'); // cleanup
        });

    }


    })();

`

**Comment by ecommgeek** [comment]
I'm new to Angular and a lot of this code is over my head so it may take a while to integrate.  Lots to learn :) 

Thanks for the help!
