### ISSUE TITLE
depends on bootstrap.min.js

### ISSUE THREAD

**Issue by mschwartz** [summernote/angular-summernote#21]
This is an issue because for angular, I would want to use angular-bootstrap.  This means I have to include two conflicting scripts: bootstrap.min.js and ui-bootstrap-tpls.js.  That is, if I don't include bootstrap.min.js, angular-summernote throws an error - it must be calling something in that javascript directly (summernote is).

The problem is they conflict.  I have a dropdown menu on my nav bar and with both those loaded, I have to click twice to open the dropdown.  If I remove either, I only have to click once, but summernote stops working.

Suggestions?

**Comment by scne** [comment]
@mschwartz I'm usign `ui.bootstrap` module but I've still a lot of troubles :sos:
