### ISSUE TITLE
How can I get the editor object outside the on-image-upload event?

### ISSUE THREAD

**Issue by Pyohwan** [summernote/angular-summernote#37]
Hello.
I like angular-simmernote and I have a question.
I can upload a image using 'editor' object. 'editor' object is on-image-upload's parameter. 
This object can be used only inner on-image-upload. 
I'd like to use 'editor' object outside the on-image-upload too.

Thanks.

**Comment by outsideris** [comment]
Did you mean second parameter, `editor`, in [onImageUpload](http://summernote.org/#/features#callbacks-onImageUpload)?
If so, I just followed summernote's API.
Can you provide the use case for use `editor` object outside the callback?

**Comment by Pyohwan** [comment]
I added a button which is irrelevant to summernote's picture toolbar to upload a image.
If click this button, upload a image to server and return URL which is accessible to image, from server.
I'd like to append image URL at summernote's editor.
So, I have to access editor object outside the onImageUpload.

**Comment by outsideris** [comment]
In such case, can you use `ngModel`?
I think you can add image url into editor if you add it into `ngModel`.

**Comment by Pyohwan** [comment]
<code>
function DemoController($scope) {
  $scope.text = "Hello World";
}
</code>
This sample code is reset "Hello World" to $scope.text.
Is it possible insert a image using ngModel in cursor position?

I have a time and searched this issue at Summernote.

https://github.com/summernote/summernote/issues/282
<code>
var editor = $.summernote.eventHandler.getEditor();
</code>

Look at HackerWins's comment on comment list. Summernote provide plugin and can access editor object. editor object can use functions insertText, insertImage, createLink....

I think angular-summernote needs that function. What do you think?

**Comment by outsideris** [comment]
@Pyohwan 
Sorry for late. I understand the problem.

`<summernote editor="editor">` 

How about do you think the attribute name?

Actually, I already used `<summernote editable="editable">` for callbacks. 
But I worried about the attribute name is too general. And `editor` is also general.
And `editor` could be confuse with `editable`.
Do you have a idea fot it?

**Comment by Pyohwan** [comment]
How do you think adding prefix like <code>ng-</code> of Angular Core module?
<code><summernote sm-editor="editor" sm-editable="editable"></code>
sm means Summernote.
But it's up to you.

**Comment by outsideris** [comment]
@Pyohwan 
I digging the issue. but summernote return editor object globally, not per summernote instance.
so, `$.summernote.eventHandler.getEditor()` return always same object.
Therefore, developer can get `Editor` via `summernote` instead `angular-summernote`.
And then, they use it with `editable` obtain from `angular-summernote`

DId I missed something? How do you think?

**Comment by Pyohwan** [comment]
That's ok.
Thank you for your help.
