### ISSUE TITLE
Uncaught TypeError: Cannot read property 'lang' of undefined

### ISSUE THREAD

**Issue by doczoidberg** [summernote/angular-summernote#38]
I did include the german language file of summernote and use `lang="de-DE"` in my sumemrnote directive. But I am getting the error: `Uncaught TypeError: Cannot read property 'lang' of undefined`

**Comment by outsideris** [comment]
@doczoidberg 
Can you explain more detail for the issue? Because I can't reproduce it.
In my [test](http://jsfiddle.net/outsider/16xL9np9/1/embedded/result%2Chtml%2Cjs%2Ccss/), there is no error.

**Comment by doczoidberg** [comment]
this seams to be a summernote problem. => https://github.com/summernote/summernote/issues/851
