### ISSUE TITLE
Angular ng-model not updating on change

### ISSUE THREAD

**Issue by matisoffn** [summernote/angular-summernote#41]
http://jsfiddle.net/n8dt4/150/

An example of the problem I am having can be seen in the fiddle above.

I have a function on my controller that uses `$scope.text`, but when using `ng-model` on the summernote directive the text is empty after typing in the textarea.

Typically in Angular, if I had a normal textarea or text input with the `ng-model` directive and after it has been typed in if I log it to the console it has the contents.

The contents of `$scope.text` do not appear using `ng-model` on the summernote directive.

To test it, type text into the textarea above the "alert it" button and then click the alert it button.  It should alert with the text but it does not.

**Comment by matisoffn** [comment]
@outsideris it's not a problem when the model is already set, but when it updates.  For example (as shown in the fiddle from the OP), a textarea with the summernote directive AND an ng-model does not work.  When you type into the textarea and then try to alert or console.log or get the value it hasn't updated.

**Comment by outsideris** [comment]
@matisoffn 
As I said, I can't reproduce it.
<https://www.youtube.com/watch?v=7gr1JQFY9Z8&feature=youtu.be>
Look at it. There are something I missed when I reproduce it?

**Comment by matisoffn** [comment]
Watched the video.  That's the desired effect, however, when I use it it does not recognize that the model has changed.

This is the piece of code I had:

<summernote height="150" config="options" ng-model="message.reply"></summernote>

$scope.options = {
height: 300,
focus: true,
airMode: true,
toolbar: [
        ['edit',[]],
        ['headline', []],
        ['style', []],
        ['fontface', []],
        ['textsize', []],
        ['fontclr', []],
        ['alignment', []],
        ['height', []],
        ['table', []],
        ['insert', []],
        ['view', []],
        ['help', []]
    ]
};

**Comment by outsideris** [comment]
Can you provide a example from <http://jsfiddle.net/n8dt4/152/>?

**Comment by matisoffn** [comment]
Mmm.  Must be something else conflicting with the summernote directive.  Thanks, will let you know what the problem is once I figure it out.

**Comment by outsideris** [comment]
@matisoffn 
Good. Let me know if you have some problem.

**Comment by gpolucci** [comment]
Hey. Whatever happened with this?   I'm using angular sumernote on a div with a model binding directive (ng-model), and it's just ignoring everything I try. No association with the model whatsoever.

**Comment by outsideris** [comment]
@gpolucci Can you show your code?

**Comment by gpolucci** [comment]
Thanks man. I fixed it. My versions were out of whack. All my bad.
G

From: "JeongHoon Byun (aka Outsider)"
Reply-To: summernote/angular-summernote
Date: Friday, April 8, 2016 at 11:39 AM
To: summernote/angular-summernote
Cc: "gerry@smartparents.com<mailto:gerry@smartparents.com>"
Subject: Re: [summernote/angular-summernote] Angular ng-model not updating on change (#41)


@gpolucci<https://github.com/gpolucci> Can you show your code?

**Comment by outsideris** [comment]
Good to hear that.
