### ISSUE TITLE
How to make font size work?

### ISSUE THREAD

**Issue by npearson72** [summernote/angular-summernote#44]
I'm not able to get the font size button to appear or work. Any ideas?

**Comment by Pyohwan** [comment]
What is your summernote version?
'font style' and 'vidio' are changed to plugin in summernote v0.6.1
Look at the summernote features page.

**Comment by npearson72** [comment]
How do you use plugins with this library?

**Comment by npearson72** [comment]
I added the plugin and it gets loaded:

`< script src="plugin/summernote-ext-fontstyle.js"></script >`

But when I add it to my toolbar the button does not show up:

`['group', [ 'fontstyle' ]]`

**Comment by npearson72** [comment]
I figured it out, you need to use:

`['group', ['fontsize']]`

**Comment by outsideris** [comment]
Sorry I don't have time to debug it now.
I will check it soon.

**Comment by npearson72** [comment]
No problem. Thanks for taking a look.

**Comment by nflorentin** [comment]
I'm interested in the answer, I'm having the same error

+1

**Comment by outsideris** [comment]
I found the bug but it's summernote's bug.
if you apply [this patch](https://github.com/summernote/summernote/pull/904/files#diff-feef9a79654f7d80a6637a0c898eb8bdR234), you can use the plugin.
I'm asking core team why this patch is missed in 0.6.2

Anyway, use toolbar like this: 
```
toolbar: [
  ['group1', ['strikethrough', 'superscript', 'subscript']], // not 'fontstyle'
  ['group2', ['fontsize']]
]
```

**Comment by outsideris** [comment]
It will be fixed in summernote v0.6.3.

**Comment by npearson72** [comment]
Excellent, thank you!

So the interface is to use `fontsize` not `fontstyle`?

**Comment by outsideris** [comment]
Yes. `fontsize` is for font-size. and `'strikethrough', 'superscript', 'subscript'` is for font-style.

**Comment by npearson72** [comment]
I guess what I'm still confused about is that I thought `fontstyle` was a plugin? In other words, I thought that the font-size functionality was pulled out into a plugin that is invoked with `fontstyle` -- am I wrong?

So in 0.6.3, will the font-size functionality be available as part of the core summernote, or will the plugin still be required?

**Comment by outsideris** [comment]
I agreed. There are some confusing with terms. 
"fontstyle" is plugin name and it is extracted core summernote since [0.6.0](https://github.com/summernote/summernote/releases/tag/v0.6.0).
So, you can use `strikethrough`, `strikethrough`, `subscript`, `fontsize` in "fontstyle" plugin and `plugin/summernote-ext-fontstyle.js` is required.

**Comment by npearson72** [comment]
Ok, cool. Thanks. Would you like to close this ticket or keep it open until 0.6.3 when I try it out?

**Comment by outsideris** [comment]
@npearson72 
I want to keep this open to track the issue.

**Comment by npearson72** [comment]
Sounds good, thanks.

**Comment by outsideris** [comment]
@npearson72 summernote [v0.6.3](https://github.com/summernote/summernote/releases/tag/v0.6.3) has been released.
Please check it again.

**Comment by npearson72** [comment]
Thanks for the update. For some reason passing the options into the config setter does not work?

You can see my code in the screenshot and what it spit out onto the screen in the other screen shot. See how the values are on the scope, but not working?

Am I doing something wrong?

![screen shot 2015-04-08 at 3 10 32 pm](https://cloud.githubusercontent.com/assets/1323414/7056543/859365ca-de01-11e4-9b2f-b16db6b42fc8.png)
![screen shot 2015-04-08 at 3 10 19 pm](https://cloud.githubusercontent.com/assets/1323414/7056544/859ff678-de01-11e4-9942-f547c9c48911.png)

**Comment by outsideris** [comment]
I couldn't find any problem in your code in screenshot.
But you have to specify `strikethrough`, `strikethrough`, `subscript`, `fontsize` in toolbar if you want to use.
(Why is `fontsize` part in commented?)

Anyway, I add [a small example](http://jsfiddle.net/outsider/n8dt4/158/) in jsfiddle.
Can you find how to solve your problem in above example? Or you want to use something differently?

**Comment by npearson72** [comment]
Seems this is an issue with 0.6.3

https://github.com/summernote/summernote/issues/1009

As you can see, even on the summernote site this is a problem:

![screen shot 2015-04-10 at 1 59 57 am](https://cloud.githubusercontent.com/assets/1323414/7084769/586d0c7a-df25-11e4-975b-7b96014a789b.png)

**Comment by outsideris** [comment]
@npearson72 You are right. It seems fixed in 0.6.4.
Sorry, Please check again.

**Comment by npearson72** [comment]
Just wanted to confirm. All is working splendidly! Thanks so much for all the help on this! Great library... great community.

**Comment by outsideris** [comment]
:+1:
