### ISSUE TITLE
Clean text on paste

### ISSUE THREAD

**Issue by Appfabrikken** [summernote/angular-summernote#47]
How can I use the on-paste event to clean the pasted text (i.e. remove all formatting code)?

When using on-paste="snPaste()", and then 
$scope.snPaste = function() {
        console.log("Pasted something");
    };

The pasted text is the content of the function. How can I fetch the original pasted content, edit it, and then paste it into the editor?

**Comment by outsideris** [comment]
Use `on-paste="snPaste(evt)", and then 

```
$scope.snPaste = function(e) {
    console.log(e.originalEvent.clipboardData.getData('text')); // pasted content
};
```

And edit pasted content with ngModel.

**Comment by alexsamant** [comment]
Actually, updating the model is not that straightforward, because the copy/paste is happening outside of Angular, so this is the full function: 


	$scope.snPaste = function(e) {
    	
    		//First define the clean content
                var cleanUp=e.originalEvent.clipboardData.getData('text');
	
	        //Have it wait for 0.5 seconds, before using $apply to update yourModel
                 setTimeout(function () {
	             $scope.$apply(function () {
	                 $scope.yourModel = cleanUp;
	             });
   		 }, 500);

	};

**Comment by outsideris** [comment]
@alexsamant 
Why is dealying 500ms needed?

**Comment by outsideris** [comment]
@alexsamant 
You're right, but I think `$timeout` is better than `$apply`.

**Comment by alexsamant** [comment]
Yea, eitherway ... it works. :)

**Comment by loter** [comment]
so if the same word is pasted twice, how to append it into the right cursor position?
