### ISSUE TITLE
how to user video button?

### ISSUE THREAD

**Issue by ralf79** [summernote/angular-summernote#48]
I want to use video toolbar button.

So I add summer note video plugins.
bower_components/summernote/plugin/summernote-ext-video.js

video button show in my summernote editor but it is not working.

What should i do?
Could you tell me What are the things in order to be to work correctly the video button?

**Comment by Pyohwan** [comment]
It seems to me that it's Summernote problem.

**Comment by outsideris** [comment]
I agreed with @Pyohwan .
You ask it in summernote. 
Anyway, you should provide more detail for your problem, not just "not working".
