### ISSUE TITLE
Insert at Caret Position

### ISSUE THREAD

**Issue by yhinds** [summernote/angular-summernote#51]
Anyway to include the Insert Text at Cursor Position added to V0.6

editor.insertText($editable, 'hello ');

Review comments here: https://github.com/summernote/summernote/issues/282#issuecomment-62831072

**Comment by easylogic** [comment]
if you can use v0.6.4 , use a new summernote's api . 

```javascript
$("#summernote").summernote("insertText", "hello"); 
```

refer to http://summernote.org/#/deep-dive

**Comment by outsideris** [comment]
In v0.4.0, angular-summernote expose summernote element via `editor` attribute.
So, you can use summernote APIs on the element.
