### ISSUE TITLE
on blur to include toolbar

### ISSUE THREAD

**Issue by alirezamansoori** [summernote/angular-summernote#54]
currently onblur gets called if toolbar is clicked. Is it possible to keep from calling onblur when toolbar is clicked?

**Comment by outsideris** [comment]
angular-summernote is wrapper for summernote.
I think it is summernote's behaviour. Could you ask it in summernote?

**Comment by alirezamansoori** [comment]
I'll close this one ..Blur should only work on form fields and not divs. Only ones that get buggy are the toolbar dropdown buttons. Will ask on summernote.
thanks.

**Comment by melatawy** [comment]
@alirezamansoori 
I have this problem in normal summernote, not the angular one.... How did you solve it? I couldn't find the solution elsewhere...

**Comment by alirezamansoori** [comment]
@melatawy It's been a while - six months since I last looked through the summernote.js. I also remember my solution wasn't perfect so I didn't use it for too long and ended up writing a simple directive that had its own toolbar with less options to use with the summernote js library. So I don't recommend what my old solution was. But I think it was something like this....
it included adding 
```
if (angular.isDefined($attrs.onToolbarClick)) {
      summernoteConfig.onToolbarClick = function() {
        $scope.toolbarclick({evt:evt});
      };
    }
```
to the controller
and adding 
`toolbarClick: '&onToolbarClick'`
to the directive scope.

Again I'm going off memory just looking at what the latest updates.. (which looks pretty good :+1: ) on angular-summernote js . So I'm sure there are holes all over it.

Hope this helps,
