### ISSUE TITLE
adding toolbarclick

### ISSUE THREAD

**Issue by alirezamansoori** [summernote/angular-summernote#55]
nothing big. I've added the following to my code to bring in on toolbar click functionality
summernoteConfig.ontoolbarclick = function (evt) { $scope.toolbarclick({ evt: evt }); };

and

.directive('summernote', [function() {
    ...
      scope: {
        ...
        toolbarclick: '&onToolbarclick',
        ...
      },
      ...
    };

**Comment by outsideris** [comment]
All event listeners I used are emitted by summernote.
I think Issuing it in summernote is better. I will add the event listeners if summernote support it.

**Comment by alirezamansoori** [comment]
ontoolbarclick has been added to summernote.

**Comment by outsideris** [comment]
@alirezamansoori Sorry. I missed it. I will check new version.

**Comment by hackerwins** [comment]
@alirezamansoori Thanks for reporting.
`onToolbarClick` was removed while refactoring. Could I ask you why this callback needed for your case?

**Comment by alirezamansoori** [comment]
Both of the following cases would cause on-blur to fire. Case 1: Clicking anywhere outside of the editor. Case 2: Clicking on the toolbar or any controller on the toolbar.
My workflow at the time created the need to distinguish the on blur if caused by clicking on a toolbar/toolbar menu items vs if clicked outside. ontoolbarclick helped with that.
For another instance I blocked any action by onblur if it was fired off due to clicking a menu item.

let me know if onblur now doesnt fire off when menu is clicked.

@hackerwins , @outsideris and team thanks for all your hard work guys.

**Comment by gelinger777** [comment]
is there any way to distingwish inside the onBlur event if it was click on toolbar or no? like 
```

onBlur(){


if(clickOnToolbar){
doThis();
}
else{
dontDoThis();
}

}
```


????
