### ISSUE TITLE
Now editor in OnImageUpload callback func is not available in latest version of summernote

### ISSUE THREAD

**Issue by monad98** [summernote/angular-summernote#56]
Hi
How can I get editor now?

**Comment by monad98** [comment]
I've added this to this.activate in angular-summernote.js
    if(angular.isDefined($attrs.note)) {
        $scope.note = element;
      }
and added "note" to directive isolated scope like this : note:'='
then, added in my controller
    $scope.note.summernote('insertImage',url);

It works. If there is better way, please let me know.
Thank you.

**Comment by outsideris** [comment]
I think this issue is similar with #37 .
You can see my last comment in #37 . Is it helpful for your problem?

**Comment by jkpatil211** [comment]
Hii
I too want to access the editor object but it shows undefined in onImageUpload function

**Comment by jkpatil211** [comment]
Actually the problem is with new version of summernote.js
When I used old one it solved my issue.

**Comment by outsideris** [comment]
@jkpatil211 I got what you mean.
I'm preparing to make it compatible with new version of summernote. So, it will a way for exposing editor object.

**Comment by kibray** [comment]
Sorry but it's two days that I'm trying to figure out how to access the editor. 
I have just uploaded to the version 0.8.1 and I read documentation and all the issued opened and closed about this topic, but still nothing, I can get the image in the editor (before updating was working well).

This is my code: 
`<summernote ng-model="text" 
		config="summeroptions"
		on-image-upload="imageUploaded(files)"
	        on-paste="paste(evt)"
		editable="editable"
		editor="editor">
</summernote>

$scope.summeroptions = {
      toolbar: [
        ['style', ['bold', 'italic']],
        ['insert', ['picture']]
      ]
};

$scope.imageUploaded = function(files) {
     console.log('image upload:', files);
     console.log('image upload\'s editor:', $scope.editor);
     console.log('image upload\'s editable:', $scope.editable);
}
`

And this is what I get in console:

image upload: FileList {0: File, length: 1}
image upload's editor: undefined
image upload's editable: undefined

Can anyone please tell me what I'm doing wrong?
thanks

**Comment by outsideris** [comment]
@kibray What browser and what version of summernote did you use?

**Comment by kibray** [comment]
@outsideris thank you for your replay.
I'm using Chrome and Summernote v.0.8.1
I finally understood where was the problem, I was using an ng-if inside the directive <summernote></summernote> and apparently this way doesn't work. I tried with ng-show/ng-hide and It finally returns the editor but now I got an Angular(v 1.4.7) issues: 'Referencing a DOM node in Expression'.
