### ISSUE TITLE
Image Upload with REST Endpoint

### ISSUE THREAD

**Issue by kiddo13** [summernote/angular-summernote#58]
I'm trying to use image upload to our REST endpoint for uploading image file.
The problem is I couldn't find any documentation on this subject for angular-summernote and in my experiment with on-image-upload="imageUpload(files, editor)" function, I got undefined on editor object.
```
$scope.imageUpload = function(files, editor) {
    console.log(files);  // FileList
    console.log(editor);  // undefined
    console.log($scope.editable); // undefined
};
```

And also there is no example for inserting the image to the editor.
Please guide me on this problem if there is anything wrong with my code above.

**Comment by Pyohwan** [comment]
Look at onImageUpload on this URL.
http://summernote.org/#/deep-dive#callbacks

editor object is no longer used.
Summernote has been upgrade.

**Comment by outsideris** [comment]
Summernote APIs have been changed in v0.6.4.
So you can get `editor` object via `editor` attribute in v0.4.0. 
<https://github.com/summernote/angular-summernote#event-listeners>

**Comment by MissCuriosity** [comment]
I have also met this problem.Have you got any solution?
