### ISSUE TITLE
In airMode toolbar gets hide when i click on any drop menu in toolbar.

### ISSUE THREAD

**Issue by sanyam-j** [summernote/angular-summernote#60]
Hi,

I am getting this issue in my application and not able to found any reason for it. Can any help me out.

My application link is https://intense-wildwood-2005.herokuapp.com/#/

**Comment by sanyam-j** [comment]
I have found the reason for the issue. This issue is injected due to the new version release of summernote #v0.6.7.

**Comment by outsideris** [comment]
As you know. it related with [summorenote/#1093](https://github.com/summernote/summernote/issues/1093)
