### ISSUE TITLE
New version 0.4.0 throughing error "Uncaught RangeError: Maximum call stack size exceeded" in console

### ISSUE THREAD

**Issue by sanyam-j** [summernote/angular-summernote#62]

**Comment by outsideris** [comment]
@sanyam-j  Could you find the case the error occured?

**Comment by sanyam-j** [comment]
While selecting the font style.

**Comment by outsideris** [comment]
@sanyam-j Thanks. I will check it.

**Comment by outsideris** [comment]
@sanyam-j Is it occured in airmode only?

**Comment by sanyam-j** [comment]
Yes i have checked in air mode. I have not checked in simple toolbar.
