### ISSUE TITLE
Cannot get paste event to fire

### ISSUE THREAD

**Issue by spdaly** [summernote/angular-summernote#64]
I have been trying to get the paste event to fire so that I can clean up crappy Word HTML.  I have yet to get it to work correctly.

Thoughts??

Here's my tag:

```
<summernote focus config="vm.options" ng-model="vm.body" on-paste="paste()">
            </summernote>
```
My options
```
        vm.options = {
            focus: true,
            toolbar: [
                ['style', ['bold', 'italic', 'underline']],
                ['fontclr', ['color']],
                ['alignment', ['ul', 'ol']],
                ['insert', ['link']]
            ]
        };
```

And my function
```
$scope.paste = function(e) { console.log('Called event paste'); }
```

**Comment by spdaly** [comment]
I found the issue. I had a left over summernote.js from another bower library being loaded. Not the correct summernote JS file per your docs.

**Comment by outsideris** [comment]
@spdaly 
So, is it solved?

**Comment by spdaly** [comment]
Yes, it is solved. Sorry, I must have forgotten to close.
