### ISSUE TITLE
Inserting an image -  appends it outside when the caret is not inside editor

### ISSUE THREAD

**Issue by Bhasuri** [summernote/angular-summernote#65]
Hello,

When I try to upload an image, the image is appended outside the editor if I have not selected (initialised the caret). I don't know what is it called technically. I tried focus but didn't work. Is there something I am missing?

I upload my image to Amazon s3 and this is what I wrote in success callback.

//I get my url here and filename too
http://snag.gy/vQwiP.jpg

http://snag.gy/qOT4v.jpg

**Comment by outsideris** [comment]
Can you show your example code?

**Comment by Bhasuri** [comment]
sure. I am hiding few credentials. This method is called onImageUpload. And as I mentioned, this worked fine if I select the editor, but not if I click somewhere else outside the editor and click on image upload.

function sendFile(file,editor,layoutInfo) {
formData = new FormData();
var filename = file.name;
var domain = "";
if(CURRENT_DOMAIN_USER)
domain = CURRENT_DOMAIN_USER.domain+"/";
if(!isValidString(file.name)){
if(CURRENT_DOMAIN_USER){
filename = CURRENT_DOMAIN_USER.domain + (new Date).getTime();
}
}
var extension = getExtention(file.type);	
formData.append('key', "editor/"+domain+filename+"."+extension);
formData.append('AWSAccessKeyId', 'XXXX');
formData.append('acl', 'public-read');
formData.append('content-type', file.type);
formData.append('policy',XXXXX');
formData.append('signature', 'XXXX');
formData.append('success_action_status', '201');
formData.append('file', file);
$.ajax({
data: formData,
dataType: 'xml',
type: "POST",
cache: false,
contentType: false,
processData: false,
url: "https://mybucket.s3.amazonaws.com/",
success: function(data) {
// getting the url of the file from amazon and insert it into the editor
var url = $(data).find('Location').text();
var img = $('<img src="'+ decodeURIComponent(url)+'"/>');
var editor = $.summernote.eventHandler.getModule();
editor.insertImage($('.note-editable'),decodeURIComponent(url),$(data).find('Key').text());
}
});

**Comment by Bhasuri** [comment]
Hi,
If you dont mind, can I know when this can be fixed?

**Comment by tjsail33** [comment]
This is likely an issue with Summernote itself, not the angular-summernote directive. You should post the issue over there.

**Comment by outsideris** [comment]
Sorry for late.
I think @tjsail33 is right, and I saw you post the issue in summernote already. (https://github.com/summernote/summernote/issues/1204)

**Comment by simonlinj** [comment]
I'm trying to use insertImage, but got undefined method. Am I doing something wrong?

```
console.info($scope.editor);
console.info($scope.editable);
$scope.editor.insertImage($scope.editable, response.url);
```

console log
```
[Log] [ (articles.client.controller.js, line 80)
<div class=​"summernote ng-isolate-scope ng-valid ng-touched ng-dirty ng-valid-parse" ng-model=​"content" config=​"options" on-init=​"init()​" on-focus=​"focus(evt)​" on-blur=​"blur(evt)​" on-change=​"change(contents)​" on-toolbar-click=​"toolbarClick(evt)​" on-image-upload=​"imageUpload(files)​" editable=​"editable" editor=​"editor" style=​"display:​ none;​">​</div>​
]
[Log] [ (articles.client.controller.js, line 81)
<div class=​"note-editable panel-body" contenteditable=​"true" style=​"height:​ 500px;​">​</div>​
]
[Error] TypeError: undefined is not a function (evaluating '$scope.editor.insertImage($scope.editable, response.url)')
	onSuccessItem (articles.client.controller.js, line 82)
	value (angular-file-upload.min.js, line 6)
	onload (angular-file-upload.min.js, line 6)
```

**Comment by simonlinj** [comment]
but it does work with `$.summernote.eventHandler.getModule(); `

**Comment by cowenchin** [comment]
$scope.editor.summernote('insertImage', response.url, file_name);
