### ISSUE TITLE
$compile not working

### ISSUE THREAD

**Issue by RahulPrabhune** [summernote/angular-summernote#70]
To improve performance on page load i would like to load <summernote> directive on edit button click. For that I am doing this 
```$(#id).append($compile("<summernote ng-model="data"><summernote>")($scope))
```
Which is not working....

Please let me know is there is a better way to do it.

Thanks
Rahul

**Comment by outsideris** [comment]
Do you want defet initialization #23 ?

**Comment by RahulPrabhune** [comment]
Yes Please

**Comment by outsideris** [comment]
Ok, It will be handle in #23 .
