### ISSUE TITLE
Appending a document in angular summernote

### ISSUE THREAD

**Issue by xaniuskarlhall** [summernote/angular-summernote#72]
Is it possible for adding a custom button for inserting a link to download a pdf file?

**Comment by outsideris** [comment]
You can do it by writing plugins. See [this](http://summernote.org/#/deep-dive#plugin) for details.

**Comment by xaniuskarlhall** [comment]
I have tried implementing this feature however I am still not clear on what to do because to me the documentation does not give enough information
