### ISSUE TITLE
implement insert a file path in summernote 

### ISSUE THREAD

**Issue by xaniuskarlhall** [summernote/angular-summernote#74]
I am using Lararvel 5 with angular-summernote. Additionally, I am having problem trying to implement a insert file path in summernote. What I am trying to accomplish is that when a user clicks on the insert file button, the user would be prompt with a modal box which has a dropdown list of all the documents that have uploaded using a feature I created within my web app. When they have selected a file from the dropdown, a anchor tag is inserted into summernote. Was wondering how could I accomplish all of this ?

**Comment by outsideris** [comment]
This is the wrapper of summernote. I think your question is related with summernote not angular-summernote.
Anyway, your issue seems be resolved [insertNode API](http://summernote.org/#/deep-dive#api) or [plugin](http://summernote.org/#/deep-dive#plugin).
