### ISSUE TITLE
Support summernote v0.7.0

### ISSUE THREAD

**Issue by Oviglo** [summernote/angular-summernote#80]
Hi,
I have an arror with the lsat version of Summernote:
TypeError: element.code is not a function line 90:
element.code(ngModel.$viewValue || '');

**Comment by outsideris** [comment]
[In Demo](http://jsfiddle.net/outsider/n8dt4/231/embedded/result%2Chtml%2Cjs%2Ccss/), there is no error.
So, I need more details. @Oviglo

**Comment by Oviglo** [comment]
Ok, you use the Summernote v0.6.16, but your module don't wrok with the version 0.7.0
https://github.com/summernote/summernote/tree/develop/dist 

Thanks.

**Comment by outsideris** [comment]
I got it. v0.7.0 doesn't release yet.

**Comment by atom0s** [comment]
Also have this issue. Need to use summernote 0.7 in my project for video support.

**Comment by peruzzo** [comment]
+1

**Comment by rpalacio86** [comment]
+1

**Comment by wtwei** [comment]
TypeError: element.summernote is not a function

**Comment by outsideris** [comment]
@wtwei Did you include summernote.js?

**Comment by wtwei** [comment]
@outsideris That is the question. I think that angular-summernote contains summernote

**Comment by outsideris** [comment]
@wtwei No, it is a just wrapper. You should include summernote.js like [a example](https://github.com/summernote/angular-summernote/blob/master/examples/index.html).

**Comment by vani12345** [comment]
Same error. Included summernote.js. Any solution?

**Comment by atom0s** [comment]
@vani12345 Upgrade your summernote and angular-summernote versions. They are working fine now.

**Comment by vani12345** [comment]
I have angular-summernote version 0.7.1 and summernote version 0.7.3 . This are the latest in github

**Comment by outsideris** [comment]
@vani12345 What is your error exactly, and does it ocurred alwaty?

**Comment by vani12345** [comment]
element.summernote is not a function at activate.... on angular-summernote.js at line 71 and 163 

Yes, it occurs always.

**Comment by outsideris** [comment]
It looks like there is no summernote.js. In [demo](http://jsfiddle.net/outsider/n8dt4/271/embedded/result%2Chtml%2Cjs%2Ccss/), no error occured. It uses angular-summernote version 0.7.1 and summernote version 0.7.3. 
I need more information such as browser or OS.
Can you load summernote editor witout angular-summernote?

**Comment by vani12345** [comment]
I am using require to load the modules..
in the require.config, I have paths for summernote.js and angular-summernote.js
in shim,     'summernote':{
       exports: 'summernote'
    },
    'angular-summernote':[
       'angular',
       'summernote'
    ]

In the require ['summernote', 'angular-summer-note'], function (....){}
In the module, I have 'summernote' dependency and in html, using <summernote></summernote>

The issue is not browser specific, as I have same problem in IE and chrome.
i guess there is something wrong with require loading.

Any help would be appreciated. Thanks in advance.

**Comment by Dihan2715** [comment]
@vani12345 Hey, I found the solution here: http://stackoverflow.com/questions/26681675/how-to-use-summernote-with-angularjs. Hope it help
