### ISSUE TITLE
ngModel binding not working in v0.51

### ISSUE THREAD

**Issue by Jeroen06** [summernote/angular-summernote#84]
When I use angular-summernote v0.51 ngModel binding don't seem to work?

It's working with v0.50: http://jsfiddle.net/fc1xmpgz/
But with v0.51 this example isn't working: http://jsfiddle.net/fc1xmpgz/3/

Or am I doing something wrong?

**Comment by dimaShin** [comment]
I have the same issue. My case can be fixed if change require params of ngModel (require it without ^)
https://gist.github.com/dimaShin/bbae09a6f9172d47ff1f

Or you can set ng-model on parent DOM element

**Comment by outsideris** [comment]
I will check it.

**Comment by id-nicola** [comment]
Same thing as @Jeroen06 is happening to me too.

**Comment by DivyaEnjoyneer** [comment]
@outsideris I got struck up with summernote('code').I'm using summernote-0.8.3 version. summernote('code') is not pulling the data from the editor.What I need to do to retrieve the changes of text in the editor & also to call a function when there is change of text in the editor.
Initialized summernote with the below function.
scope.initializeSummernote = function() {
        $('.summernoteWYSWIG').summernote({
            placeholder: 'Enter your message place images and videos...',
            onChange: scope.updateMessage
        });
    };
& using $('.summernoteWYSWIG').summernote('code'); for retreiving the data.
[summernote.zip](https://github.com/summernote/angular-summernote/files/975397/summernote.zip)

Thanks in Advance.
