### ISSUE TITLE
Issue with model binding in 0.5.1

### ISSUE THREAD

**Issue by zacharyclaysmith** [summernote/angular-summernote#87]
I was using angular-summernote 0.5.1 with angular 1.3.4 within a directive.

The summernote directive refused to observe the ng-model attribute (I attempted to get it working for about 5 hours). Essentially, I was setting the ng-model attribute to existing text (HTML and non-HTML) and nothing ever showed up within the summernote element.

In the end, I downgraded to angular-summernote 0.4.2 and everything worked perfectly. I'm not sure if there's a documenation gap between the versions, a problem arising from the compatibility upgrades in 0.5.1 with angular 1.4.x, OR if this is just a pure bug in 0.5.1, and don't have time to pursue it much further. I wish I could be more thorough and give code examples, but I don't have much time right now, other than to make a note of this. Let me know if you need more info, and I'll see what I can do.

**Comment by outsideris** [comment]
It fixed in #84 and I released 0.5.2.
