### ISSUE TITLE
Events don't appear to be working

### ISSUE THREAD

**Issue by IonutBajescu** [summernote/angular-summernote#88]
In the scope the variable was declared as `onFocus` (1) , but later, it tries to call `focus` (2) instead - which of course doesn't give the expected behavior. 
1 - https://github.com/summernote/angular-summernote/blob/master/src/angular-summernote.js#L127
2 - https://github.com/summernote/angular-summernote/blob/master/src/angular-summernote.js#L22

I'll release a patch once the bug is confirmed. It happened to me, I'm only waiting for one person that had more coffee than me this morning to confirm.

**Comment by outsideris** [comment]
I think it fixed in #89 because summernote v0.7.0 has breaking changes. I will release new version to support summernote v0.7 soon.
Please repoen it if you are not in this case.
