### ISSUE TITLE
Placeholder are overlapped in v0.7.0

### ISSUE THREAD

**Issue by gongzza** [summernote/angular-summernote#91]
안녕하세요.

이번에 버전이 올라가면서 타이밍 이슈가 조금 생긴것 같아요.

ng-model로 설정한 부분이 네트워크로 데이터를 가져온 후에 뿌려줘서 그런건지 다음과 같이 

placeholder와 내용이 겹쳐 보이는 현상이 보입니다.

![image](https://cloud.githubusercontent.com/assets/6902005/11771548/33589c80-a255-11e5-858a-31f07e495f32.png)

그래서 저는 우선 데이터를 가져오는 콜백 함수에서 빈문자열을 입력하는 식으로 처리했어요.

```javascript
$resource.get({id: id}, function(data) {
  vm.data = data;
  $('.summernote').summernote('editor.insertText', ' ');
});
```

버전은 0.7.0 입니다.

감사합니다.

**Comment by gongzza** [comment]
확인해 보니까요 아래 부분에서 코드를 추가 하지만 summernote에서 처리가 안되는 것 같아요.
```javascript
      if (ngModel) {
        ngModel.$render = function() {
          element.summernote('code', ngModel.$viewValue || '');
        };
      }
```
에고 죄송합니다 ;

**Comment by outsideris** [comment]
네 summernote쪽 이슈로 얘기 들었는데 아직 확인은 못해봤었습니다. api로 사용할 때 placeholder와 충돌하는 것으로 보이네요. 감사합니다.

**Comment by Charkhan** [comment]
Hi,

I'm having the same problem here, grabbing data from an API and placeholder sticking around with the content. (Even thought I'm not understanding Korean lol)

**Comment by gongzza** [comment]
@Charkhan 
it will be fixed on summernote 0.7.1 [#1504](https://github.com/summernote/summernote/issues/1504)

**Comment by Charkhan** [comment]
Nice !

Thanks for the head's up !
