### ISSUE TITLE
on-media-delete 추가 부탁드립니다.

### ISSUE THREAD

**Issue by gongzza** [summernote/angular-summernote#92]
안녕하세요. 

imageUpload를 보면서 혼자 수정을 했는데요. 조금 이상하게 한것같아요;

```javascript
    if (angular.isDefined($attrs.onMediaDelete)) {
      callbacks.onMediaDelete = function(target) {
        var element = {
          target: target
        };
        $scope.mediaDelete({target:element, editable: $scope.editable});
      }
    }
```

이게 target을 바로 넘기니까요. dom을 바로 넘긴다고 에러가 나더라구요.

[Error: $parse:isecdom Referencing a DOM node in Expression](https://docs.angularjs.org/error/$parse/isecdom)

그래서 json으로 한번 감싸니까 넘어가져서 결과를 잘 받긴 하더라구요.

저는 여기까지 인것 같아요.. 잘 부탁드립니다 ~

**Comment by outsideris** [comment]
@gongzza  I added on-media-delete. Please check it and tell me what you think about this aproach.
Angular prohibit passing DOM into angular expression.

**Comment by gongzza** [comment]
@outsideris 안녕하세요 ~ 추가해주셔서 감사합니다 ~ 제가 답변이 많이 늦었네요 ㅠ
제 생각에는 완벽한 것 같아요 ㅎㅎ 감사합니다 ~

**Comment by outsideris** [comment]
@gongzza Thank you for confirmation.

**Comment by akoury** [comment]
@outsideris is there a way to get this to work when the user deletes the picture with the backspace key? currently only works if they delete it through the delete button
