### ISSUE TITLE
Air Modes does not work

### ISSUE THREAD

**Issue by JefferE** [summernote/angular-summernote#96]
If you use airMode:  true the toolbar shows up when you select text but the tools do not act on it (i.e. clicking Bold tool does not affect the text).

This happens even in your examples/index.html

**Comment by outsideris** [comment]
What is your browser?

**Comment by JefferE** [comment]
Sorry, didn't think to check that. Looks like it works on Chrome properly but not Firefox 43.0.2

**Comment by outsideris** [comment]
I confirmed it. Thank you for reporting.
This issue is related with https://github.com/summernote/summernote/issues/1510 . It will be fixed in summernote v0.7.1 that is going to release soon, and angular-summernote is expected work properly with summernote v0.7.1.

**Comment by JefferE** [comment]
Great thanks. Love it so far.
