### ISSUE TITLE
TypeError: Cannot read property 'isCollapsed' of null

### ISSUE THREAD

**Issue by outsideris** [summernote/angular-summernote#99]
related with https://github.com/summernote/summernote/issues/1564

**Comment by outsideris** [comment]
It is the issue of summernote that fixed already in the `develop` branch.

**Comment by brandonros** [comment]
How can I get a build with this fixed?

**Comment by sergiofigueras** [comment]
The same too. How can I get a new version?

**Comment by outsideris** [comment]
@brandonros @sergiofigueras I will tell summernote core team about the release schedule.

**Comment by outsideris** [comment]
fixed in summernote v0.7.2.
